export const LOGIN_USER_PATTERN = 'LOGIN_USER';
export const FIND_USER_PATTERN = 'FIND_USER';
export const FIND_USER_BY_EMAIL_PATTERN = 'FIND_USER_BY_EMAIL';
export const CHECK_USER_PERMISSION_PATTERN = 'CHECK_USER_PERMISSION';
export const INVALIDATE_SESSION_PATTERN = 'INVALIDATE_SESSION';
