/**
 * Auth Service Patterns
 * Patterns để gọi Core Service
 */

export const LOGIN_USER_PATTERN = 'LOGIN_USER';
export const FIND_USER_PATTERN = 'FIND_USER';
export const FIND_USER_BY_EMAIL_PATTERN = 'FIND_USER_BY_EMAIL';
export const CHECK_USER_PERMISSION_PATTERN = 'CHECK_USER_PERMISSION';
export const INVALIDATE_SESSION_PATTERN = 'INVALIDATE_SESSION';
export const SAVE_USER_DEVICE_PATTERN = 'SAVE_USER_DEVICE';
export const SAVE_USER_DEVICE_HISTORY_PATTERN = 'SAVE_USER_DEVICE_HISTORY';
export const GET_USER_REFRESH_TOKEN_PATTERN = 'GET_USER_REFRESH_TOKEN';
export const SAVE_USER_REFRESH_TOKEN_PATTERN = 'SAVE_USER_REFRESH_TOKEN';
export const REVOKE_USER_TOKEN_PATTERN = 'REVOKE_USER_TOKEN';
